### ISSUE TITLE
测试feign调用失败

### ISSUE THREAD

**Issue by miaoyinjun** [luo-zhan/EasyEnum#2]
请求：[http://127.0.0.1:8080/testFeign?sex=1](http://127.0.0.1:8080/testFeign?sex=1)

控制台错误：`
feign.FeignException$BadRequest: [400] during [GET] to [http://127.0.0.1:8080/feignFunction?sex=MALE] [TestFeignClient#feignFunction(Sex)]: [{"timestamp":"2024-05-21T09:20:04.767+00:00","status":400,"error":"Bad Request","message":"","path":"/feignFunction"}]
	at feign.FeignException.clientErrorStatus(FeignException.java:195) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:177) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.12.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.12.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:na]
	at com.sun.proxy.$Proxy65.feignFunction(Unknown Source) ~[na:na]
`

**Comment by luo-zhan** [comment]
已修复，谢谢反馈
